### ISSUE TITLE
block/unblock user

### ISSUE THREAD

**Issue by khanhlt** [khanhlt/GemKeK#49]
@ThanhChinhBK 
1. Admin block được admin --> Trong bảng hiện thị user thì ko hiển thị admin nữa có đc ko 
2. Khi 1 user bị block, lúc đăng nhập ko đăng nhập được thì có nên thông báo là tài khoản của bạn đã bị block vì lý do abc...  không ?

**Comment by ThanhChinhBK** [comment]
1, ok
2, bên frontend xử lý cho bắn ra một thông báo nhé

**Comment by ThanhChinhBK** [comment]
done
